# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('cover', models.ImageField(default='default.jpg', upload_to='avatar/%Y/%m/%d', verbose_name='封面')),
                ('view_nums', models.IntegerField(blank=True, null=True, verbose_name='访问量')),
                ('comment', models.TextField(verbose_name='评论')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('labels', models.ManyToManyField(to='posts.Labels')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
