# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('category', models.CharField(max_length=15, verbose_name='标签')),
                ('created_time', models.DateField(verbose_name='创建时间')),
                ('active', models.BooleanField(verbose_name='是否激活')),
                ('view_nums', models.IntegerField(verbose_name='访问量')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
        ),
    ]
