# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='封面'),
            preserve_default=False,
        ),
    ]
