# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='static/images/avatar/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
