# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0003_auto_20181026_1458'),
        ('posts', '0003_auto_20181022_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewer',
            field=models.ManyToManyField(to='userview.PostipNumber', verbose_name='访客'),
        ),
    ]
