# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='网站访问次数')),
            ],
            options={
                'verbose_name': '视频解析访问量统计',
                'verbose_name_plural': '视频解析访问量统计',
            },
        ),
    ]
