# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_playernumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostipNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_view_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '文章访问信息',
                'verbose_name_plural': '文章访问信息',
            },
        ),
        migrations.AddField(
            model_name='userip',
            name='last_view_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后访问时间'),
        ),
    ]
